DROP TABLE IF EXISTS export_task_run;

CREATE TABLE export_task_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    run_no INT NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL UNIQUE,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    expected_count BIGINT NOT NULL DEFAULT 0,
    exported_count BIGINT NOT NULL DEFAULT 0,
    progress INT NOT NULL DEFAULT 0,
    file_name VARCHAR(255),
    file_path VARCHAR(1024),
    file_size BIGINT,
    file_expire_at TIMESTAMP,
    auto_attempt_count INT NOT NULL DEFAULT 0,
    failure_code VARCHAR(64),
    failure_message VARCHAR(1000),
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    worker_id VARCHAR(128),
    execution_token VARCHAR(64),
    heartbeat_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    last_downloaded_at TIMESTAMP,
    download_count INT NOT NULL DEFAULT 0,
    legacy_task_id BIGINT,
    UNIQUE (task_id, run_no)
);
