CREATE TABLE orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(32) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(32) NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    payment_status VARCHAR(32) NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    order_source VARCHAR(32) NOT NULL,
    item_count INT NOT NULL,
    total_amount DECIMAL(18, 2) NOT NULL,
    shipping_province VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    paid_at DATETIME NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_orders_order_no (order_no),
    KEY idx_orders_created_id (created_at, id),
    KEY idx_orders_customer_phone (customer_phone),
    KEY idx_orders_status_created_id (order_status, created_at, id),
    KEY idx_orders_payment_created_id (payment_status, created_at, id),
    KEY idx_orders_payment_method (payment_method),
    KEY idx_orders_source (order_source),
    KEY idx_orders_amount (total_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE export_task (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_no VARCHAR(48) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    export_type VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    filter_snapshot_json JSON NULL,
    snapshot_max_id BIGINT NULL,
    snapshot_time DATETIME NOT NULL,
    export_field_version INT NOT NULL DEFAULT 1,
    expected_count BIGINT NOT NULL DEFAULT 0,
    exported_count BIGINT NOT NULL DEFAULT 0,
    progress INT NOT NULL DEFAULT 0,
    file_name VARCHAR(255) NULL,
    file_path VARCHAR(1024) NULL,
    file_size BIGINT NULL,
    file_expire_at DATETIME NULL,
    auto_attempt_count INT NOT NULL DEFAULT 0,
    manual_retry_index INT NOT NULL DEFAULT 0,
    source_task_id BIGINT NULL,
    root_task_id BIGINT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(1000) NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    worker_id VARCHAR(128) NULL,
    execution_token VARCHAR(64) NULL,
    heartbeat_at DATETIME NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    last_downloaded_at DATETIME NULL,
    download_count INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_export_task_no (task_no),
    UNIQUE KEY uk_export_task_idempotency (idempotency_key),
    KEY idx_export_task_status_created (status, created_at),
    KEY idx_export_task_status_heartbeat (status, heartbeat_at),
    KEY idx_export_task_expire_status (file_expire_at, status),
    UNIQUE KEY uk_export_task_root_retry (root_task_id, manual_retry_index),
    KEY idx_export_task_source (source_task_id),
    CONSTRAINT fk_export_task_source FOREIGN KEY (source_task_id) REFERENCES export_task(id),
    CONSTRAINT fk_export_task_root FOREIGN KEY (root_task_id) REFERENCES export_task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE export_task_item (
    task_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (task_id, order_id),
    KEY idx_export_task_item_order (order_id),
    CONSTRAINT fk_export_task_item_task FOREIGN KEY (task_id) REFERENCES export_task(id),
    CONSTRAINT fk_export_task_item_order FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE export_task_attempt (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    execution_token VARCHAR(64) NOT NULL,
    worker_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at DATETIME NOT NULL,
    heartbeat_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_export_attempt_task_no (task_id, attempt_no),
    UNIQUE KEY uk_export_attempt_token (execution_token),
    KEY idx_export_attempt_task_started (task_id, started_at),
    CONSTRAINT fk_export_attempt_task FOREIGN KEY (task_id) REFERENCES export_task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbox_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(16) NOT NULL,
    publish_attempts INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME NOT NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    last_error VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbox_event_id (event_id),
    KEY idx_outbox_status_retry_id (status, next_retry_at, id),
    KEY idx_outbox_aggregate_created (aggregate_id, created_at),
    CONSTRAINT fk_outbox_task FOREIGN KEY (aggregate_id) REFERENCES export_task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
